### PR TITLE
Remove unnecessary CSS

### PR DESCRIPTION
**Pull request by hcarneiro**
- Removed unnecessary CSS because the new appearances will control these values.
```css
.mode-interact .fl-widget-instance[data-name="Primary Button"] {
  width: 100%;
}

@media (min-width:640px) {
  .mode-interact .fl-widget-instance[data-name="Primary Button"] {
    width: auto;
  }
}
```
The above will be controlled by the Appearance settings, we have set these values as the defaults in the theme config, but users can change them.

```css
@media only screen and (max-width: 640px) {
  .fl-page-editable [data-fl-edit] [data-fl-widget-instance][data-name="Primary Button"] {
    display: block;
  }
}
```
Same goes for this. This will still be the default, but users will be able to change this.

These were removed because the were being specifically targeted and overwriting the theme CSS.

### CODE REVIEW

**Comment by squallstar** [comment]
Please explain.

**Comment by squallstar** [comment]
Please explain.

**Comment by hcarneiro** [comment]
@squallstar No need to approve them just yet, so it doesn't get merged accidentally.

Added explanation to the PR description.

**Comment by squallstar** [comment]
@hcarneiro when you have a work in progress PR, add the "WIP" prefix ;)

**Comment by tonytlwu** [comment]
@hcarneiro You haven't answered [@squallstar's question](https://github.com/Fliplet/fliplet-widget-primary-button/pull/12#issuecomment-498181759).

**Comment by hcarneiro** [comment]
@tonytlwu I have but added more detail now.

**Review by tonytlwu — APPROVED** [review]

**Pull request merged**
